### ISSUE TITLE
Lots of ExpansionError exceptions since yocto 2.1

### ISSUE THREAD

**Issue by AlgorithMan-de** [openembedded/meta-openembedded#30]
Since yocto 2.1, the getVar function in bitbake/lib/bb/data_smart.py doesn't have a default value for the parameter 'expand' anymore. Because of that, meta-openembedded layers throw a lot of ExpansionError exceptions, saying getVar() missing 1 required positional argument: 'expand'.
See also https://bugzilla.yoctoproject.org/show_bug.cgi?id=3314

**Comment by shr-project** [comment]
It wasn't changed in 2.1, but in 2.3 and master is already fixed. Read README in top directory and use ML.

**Comment by AlgorithMan-de** [comment]
I see these errors in a fresh 2.2 checkout (`git clone -b morty git://git.yoctoproject.org/poky.git` as suggested on https://www.yoctoproject.org/downloads) with a fresh checkout of `git://git.openembedded.org/meta-openembedded` master as referenced on https://layers.openembedded.org and the toplevel README only says 
> Collection of layers for the OE-core universe
> Please see the respective READMEs in the layer subdirectories

Maybe git://git.openembedded.org/meta-openembedded isn't up to date?

**Comment by shr-project** [comment]
You need to use compatible branches, so use morty branch of meta-openembedded instead of master.

**Comment by JOE-JOE-NGIGI** [comment]
@shr-project I tried with compatible branches i.e morty for meta-openembedded but it still throws in that error. Any further help?

**Comment by lefamz** [comment]
@JOE-JOE-NGIGI Try to clean all files and build it from scratch. Worked for me.

**Comment by sherifomran** [comment]
try to reduce number of parallel threads used in local.conf
